Pallet `weights.rs` files without generation
centrifuge/centrifuge-chain pull request #1275
Opened 2023-03-21 13:33 UTC by lemunozm

# Description

Fixes #1267

## Changes and Descriptions

- Remove `run_benchmark.sh` script because it's no longer used after this PR.
- Clear `weights.rs` files from all pallets.
  - If there are benchmarks associated, the implementation contains `Weight::zero()`
  - If there are no benchmarks, the implementation contains a default weight value high enough to avoid security issues.
- Ensure all pallets from `centrifuge`/`altair` use their runtime-generated weights.(**double-check this**)
- Removed `bridge-mapping` stuff that seems to be deprecated (**check this**).

## Type of change

- Refactor

2023-03-21 13:35 UTC, lemunozm commented on runtime/centrifuge/src/weights/mod.rs
> +pub mod pallet_restricted_tokens;
We have been using the weights from the pallet not from the runtime for `centrifuge`. Not sure if this was the intended behavior. I've changed it in order to use the correct weights from now

2023-03-21 16:30 UTC, NunoAlexandre submitted a review, later dismissed
🧹 ✨

2023-03-22 07:39 UTC, mustermeiszer requested changes

2023-03-22 07:39 UTC, mustermeiszer commented on scripts/run_benchmark.sh
@lemunozm can we please keep this one. It definitely makes sense to run benchmarks on a single pallet for testing puposes. The other script runs it for all. I would adapt the command to just not have template and ouput. If this is possible.

2023-03-22 07:45 UTC, lemunozm commented on scripts/run_benchmark.sh
Ok, it can be simplified a lot, probably even do not need its own file, and can be run directly from `init.sh` as `./scripts/init.sh benchmark <runtime> <pallet>`, WDYT?

2023-03-22 07:47 UTC, lemunozm commented on scripts/run_benchmark.sh
The simplified command is 
```sh
cargo run --features runtime-benchmarks benchmark pallet --pallet <pallet> --chain <runtime> --extrinsic="*"
```

2023-03-22 08:09 UTC, lemunozm commented on scripts/run_benchmark.sh
Done and tested

2023-03-22 08:28 UTC, mustermeiszer approved these changes

2023-03-22 10:09 UTC, merged