Error handling for impl PoolReserve in pallet-pools
centrifuge/centrifuge-chain pull request #654
Opened 2022-02-26 15:51 UTC by stanly-johnson

resolves #646

2022-02-28 09:29 UTC, NunoAlexandre commented on pallets/pools/src/lib.rs
> +		NotEnoughFundsInPool,
```suggestion
		InsufficientReserveFunds,
```

2022-02-28 16:00 UTC, branan commented
I wonder if it makes more sense to use one of the built-in [`TokenError`](https://docs.substrate.io/rustdocs/latest/sp_runtime/enum.TokenError.html) variants instead of creating our own error?

2022-03-01 09:24 UTC, mustermeiszer commented
@branan the `TokenError` enum is not very descriptive in my opinion. The only roughly matching variant would be `TokenError::NoFunds`, that translates into  "Funds are unavailable" as the error message. I would keep it as an PoolErorr so one knows the reason directly.

2022-03-01 09:28 UTC, mustermeiszer requested changes
Thanks for the contribution @stanly-johnson! 

Referring to what @branan said, I think it makes sense to use the `TokenError::NoFunds` variant here instead of using a costume error message.

2022-03-02 23:59 UTC, branan approved these changes
Looks good to me. Once tests have run I believe we can hit the button.

Thanks for your contribution!

2022-03-03 07:30 UTC, merged

2022-03-03 07:30 UTC, NunoAlexandre commented
@stanly-johnson 👏