Include fast-runtime feature flag with some defaults
centrifuge/centrifuge-chain pull request #845
Opened 2022-06-18 00:21 UTC by mikiquantum

**Context:**
The feedback loop of testing upgrades locally (or just some operations that require Council or Democracy) is slow. The current alternative to this is to modify the runtime code only in your dev branch to test your code but that comes with potential issues down the line, unwanted commits, extra code changes that shouldn't be required among others.

**Proposal:**
I propose to include this feature flag that we can use for certain constants that usually delay the development cycle. When this the code has been compiled with this flag, the `prod_or_fast` macro developed by parity allows to pass a test value and potentially a value read from the environment at the time of compilation (the latter is the one I used here but I do not see us using it too much)

This way when running the chain locally the `init.sh start-parachain` script builds with that flag, so we can test out altair or centrifuge runtime easily and quickly. 

In addition, I propose to build a docker image as well ready for local testing, without the need to compile again the code. This is particularly useful for other teams that just want to set up a local env quickly.

Two images tags will be pushed:
- `centrifugeio/centrifuge-chain:parachain-$date-$commit`
- `centrifugeio/centrifuge-chain:test-parachain-$date-$commit`

_(note this change is not included in this PR yet)_

2022-06-18 03:22 UTC, branan approved these changes
Maybe we should name this more generically in case there are other things we want to change based on whether we're in dev or prod? But otherwise it's a nice change and LGTM :+1:

2022-06-18 09:28 UTC, NunoAlexandre requested changes
This looks very neat 👌 TIL on `prod_or_fast`

2022-06-18 09:28 UTC, NunoAlexandre commented on runtime/altair/src/lib.rs
> +	pub VotingPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "AIR_LAUNCH_PERIOD");
```suggestion
	pub VotingPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "AIR_VOTING_PERIOD");
```

2022-06-18 09:28 UTC, NunoAlexandre commented on runtime/altair/src/lib.rs
> +	pub CooloffPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "AIR_ENACTMENT_PERIOD");
```suggestion
	pub CooloffPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "AIR_COOLOFF_PERIOD");
```

2022-06-18 09:28 UTC, NunoAlexandre commented on runtime/centrifuge/src/lib.rs
> +	pub  CooloffPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "CFG_ENACTMENT_PERIOD");
```suggestion
	pub  CooloffPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "CFG_COOLOFF_PERIOD");
```

2022-06-18 09:28 UTC, NunoAlexandre commented on runtime/centrifuge/src/lib.rs
> +	pub  VotingPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "CFG_LAUNCH_PERIOD");
```suggestion
	pub  VotingPeriod: BlockNumber = prod_or_fast!(7 * DAYS, 1 * MINUTES, "CFG_VOTING_PERIOD");
```

2022-06-18 09:28 UTC, NunoAlexandre commented on Cargo.toml
> +
```suggestion
```

2022-06-18 09:30 UTC, NunoAlexandre commented
@branan 

> Maybe we should name this more generically in case there are other things we want to change based on whether we're in dev or prod? But otherwise it's a nice change and LGTM 👍

The `prod_or_fast` macro operates with the `fast-runtime` flag: 

```
#[macro_export]
macro_rules! prod_or_fast {
	($prod:expr, $test:expr) => {
		if cfg!(feature = "fast-runtime") {
			$test
		} else {
			$prod
		}
	};
	($prod:expr, $test:expr, $env:expr) => {
		if cfg!(feature = "fast-runtime") {
			core::option_env!($env).map(|s| s.parse().ok()).flatten().unwrap_or($test)
		} else {
			$prod
		}
	};
}
```

2022-06-18 15:26 UTC, NunoAlexandre submitted a review, later dismissed

2022-06-20 14:35 UTC, NunoAlexandre reviewed
Some thoughts here:

- I wouldn't name the build with `features=fast-runtime` enabled as `test` - it's confusing since we already have other things named `test` in the CI and in the code. I'd either call it `fast`, `fast-runtime`, or give it a funnier name like `speedy` or `turbo`.

- Given how long the CI already takes to run, introducing yet another build for this `fast-runtime`-enabled package is yet another thing making it slower. Can we maybe only build this image when the commit is prefixed with, say, `[speedy]` or something like that?

2022-06-20 17:21 UTC, NunoAlexandre approved these changes
> There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors.

Not blocking this 🍻

2022-06-20 17:24 UTC, NunoAlexandre commented
> I am concerned about anyone that pulls that image because they think that is a faster version of Centrifuge, lightclient and that can cause support issues down the line when running against the production chains. I would rename to something else if `test` is not agreed on happily but any of the suggestions still imply what my initial concern is based on. Maybe `dev-*` or `dev-only-*` would make more sense.

Yeah I thought the same originally thus the funny name suggestion. Also though of `dev-*` but that's also confusing since it overlaps with the `dev` runtime genesis.

Naming things is hard. I don't know anymore 🙃 Unless if @branan comes with a good suggestion I'd say go ahead with `test` and we iterate over it afterwards if a better name comes up.

2022-06-21 18:43 UTC, merged