pallet-investments - Tests and Fixes
centrifuge/centrifuge-chain pull request #985
Opened 2022-09-20 12:14 UTC by mustermeiszer

# Description

Includes the unit tests for the pallet-investments. During testing I found a few bugs which are also fixed in the same PR. For easability of testing this also adds a Mock for the `trait InvestmentAccountant`

Closes #917 

## Changes and Descriptions
* Unit tests
* Bug fixes in investment logic
* Mock for `trait InvestmentAccountant`

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [x] Unit test for pallet-investments

# Checklist:

- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I rebased on the latest `parachain` branch

2022-09-20 12:16 UTC, mustermeiszer commented
No worries, it's just a huge test file, plus a mock, plus some bug fixes.

2022-09-20 14:18 UTC, gruberb requested changes
Beautiful 💐

I need some more time to actually understand what's going on, so I won't hold back approving. There is just one little comment where I think we can move something inside an `else` block and get rid of a variable, otherwise very nice 👍

2022-09-20 14:18 UTC, gruberb commented on libs/traits/src/lib.rs
> +/// A trait who's implementer provides means of accounting
It's actually `whose` 😄

2022-09-20 14:18 UTC, gruberb commented on libs/traits/src/mocks/accountant.rs
> +/// # Example macro usage:
Nice!!

2022-09-20 14:18 UTC, gruberb commented on pallets/investments/src/lib.rs
> +		/// The order has not been marked as cleared. It's either active or
👍

2022-09-20 14:18 UTC, gruberb commented on pallets/investments/src/lib.rs
> +		if remove_user_order {
Why not move this into the `else` block and remove `remove_user_order`?

2022-09-20 15:31 UTC, mustermeiszer commented
@gruberb addressed

2022-09-21 07:59 UTC, gruberb approved these changes
LGTM 👍

2022-09-21 12:14 UTC, gruberb approved these changes
🚀

2022-09-21 13:24 UTC, merged